#!/usr/bin/env bash
#reads the file
while IFS=: read -r username uid home; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo "---"
done < /etc/passwd
