#!/usr/bin/env bash
#reads the file passwd
while IFS=: read -r username passwd uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $passwd, more info about the user here: $gecos"
    echo "---"
done < /etc/passwd
