#!/usr/bin/env bash
#reads the file passwd
while IFS=: read -r username passwd uid  gid gecos home shell; do
     echo "The user $username is part of the $gid gang, lives in $username and rides $home:$shell. USER ID's place is protected by the passcode $passwd, more info about the user here: $uid"
    echo "---"
done < /etc/passwd
