#!/usr/bin/env bash
#uses  the if, elif and else statements
counter=1

while [ $counter -le 10 ]
do 
    if [ $counter -eq 3 ]
    then
        echo "Best School"
        echo "bad luck"
    elif [ $counter -eq 7 ]
    then	    
        echo "Best School"
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
