#!/usr/bin/env bash
#uses  the if, elif and else statements
counter=1

while [ $counter -le 20 ]
do
    case $counter in
        4)
            echo $counter
            echo "bad luck from China"
            ;;
        7)
            echo $counter
            echo "bad luck from Japan"
            ;;
        18)
            echo $counter
            echo "bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    ((counter++))
done
