#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

hour=0
while [ $hour -le 12 ]
do
    minute=0
    while [ $minute -le 59 ]
    do
        echo "$hour:$minute"
        ((minute++))
        
        # Stop at 12:59
        if [ $hour -eq 12 ] && [ $minute -eq 60 ]
        then
            break 2
        fi
    done
    ((hour++))
done
